[workspace]
authors = ["Michael P. Adams"]
channels = ["conda-forge"]
channel-priority = "strict"
name = "pixi_env"
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
numpy = "1.26.*"
scipy = ">=1.13.1,<2"
pandas = ">=2.3.1,<3"
matplotlib = ">=3.9.4,<4"
pillow = ">=11.3.0,<12"
netcdf4 = ">=1.7.2,<2"
zarr = ">=2.18.2,<3"
numexpr = ">=2.10.2,<3"
xarray = ">=2024.7.0,<2025"
tqdm = ">=4.67.1,<5"
dask = ">=2024.8.0,<2025"
numcodecs = ">=0.12.1,<0.13"
sympy = ">=1.14.0,<2"
numba = ">=0.60.0,<0.61"
bottleneck = ">=1.5.0,<2"
pyfftw = ">=0.14.0,<0.15"
pyyaml = ">=6.0.2,<7"
json5 = ">=0.12.1,<0.13"
imageio = ">=2.37.0,<3"
seaborn = ">=0.13.2,<0.14"
scikit-image = ">=0.24.0,<0.25"
scikit-learn = ">=1.6.1,<2"
pyvista = ">=0.46.1,<0.47"
pyvistaqt = ">=0.11.3,<0.12"
jupyterlab = ">=4.4.6,<5"
ipywidgets = ">=8.1.7,<9"
sphinx = ">=4.5.0,<5"
myst-parser = ">=0.18.1,<0.19"
furo = ">=2023.5.20,<2024"
breathe = ">=4.35.0,<5"
exhale = ">=0.3.7,<0.4"
mypy = ">=1.17.1,<2"
ruff = ">=0.14.6,<0.15"

